# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'AliPlayerDemo' do

  pod 'WoodPeckeriOS', :configurations => ['Debug']
  pod 'Masonry'
  pod 'AliPlayerSDK_iOS', '5.2.2' # 播放报错，有错误日志
#  pod 'AliPlayerSDK_iOS', '5.2.1' # 无法播放，连错误日志都没有
#  pod 'AliPlayerSDK_iOS', '5.1.6' # 正常播放

end
