# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'AliPlayerDemo' do

  pod 'WoodPeckeriOS', :configurations => ['Debug']
  pod 'Masonry'
  pod 'AliPlayerSDK_iOS'

end
